namespace ProfileSwitcher
{
    partial class Switcher
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// 
        /// fuck you and your stupid autogenerated warnings, VS
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Switcher));
            this.ProfileList = new System.Windows.Forms.ListView();
            this.SaveButton = new MaterialSkin.Controls.MaterialFlatButton();
            this.LoadButton = new MaterialSkin.Controls.MaterialFlatButton();
            this.TabControl = new MaterialSkin.Controls.MaterialTabControl();
            this.MainPage = new System.Windows.Forms.TabPage();
            this.SettingsPage = new System.Windows.Forms.TabPage();
            this.TabSelector = new MaterialSkin.Controls.MaterialTabSelector();
            this.Notification1 = new MaterialSkin.Controls.MaterialLabel();
            this.TabControl.SuspendLayout();
            this.MainPage.SuspendLayout();
            this.SettingsPage.SuspendLayout();
            this.SuspendLayout();
            // 
            // ProfileList
            // 
            this.ProfileList.BackColor = System.Drawing.Color.DimGray;
            this.ProfileList.HideSelection = false;
            resources.ApplyResources(this.ProfileList, "ProfileList");
            this.ProfileList.MultiSelect = false;
            this.ProfileList.Name = "ProfileList";
            this.ProfileList.UseCompatibleStateImageBehavior = false;
            this.ProfileList.View = System.Windows.Forms.View.List;
            // 
            // SaveButton
            // 
            resources.ApplyResources(this.SaveButton, "SaveButton");
            this.SaveButton.Depth = 0;
            this.SaveButton.MouseState = MaterialSkin.MouseState.HOVER;
            this.SaveButton.Name = "SaveButton";
            this.SaveButton.Primary = false;
            this.SaveButton.UseVisualStyleBackColor = true;
            this.SaveButton.Click += new System.EventHandler(this.LoadButton_Click);
            // 
            // LoadButton
            // 
            resources.ApplyResources(this.LoadButton, "LoadButton");
            this.LoadButton.Depth = 0;
            this.LoadButton.MouseState = MaterialSkin.MouseState.HOVER;
            this.LoadButton.Name = "LoadButton";
            this.LoadButton.Primary = false;
            this.LoadButton.UseVisualStyleBackColor = true;
            // 
            // TabControl
            // 
            this.TabControl.Controls.Add(this.MainPage);
            this.TabControl.Controls.Add(this.SettingsPage);
            this.TabControl.Depth = 0;
            resources.ApplyResources(this.TabControl, "TabControl");
            this.TabControl.MouseState = MaterialSkin.MouseState.HOVER;
            this.TabControl.Name = "TabControl";
            this.TabControl.SelectedIndex = 0;
            // 
            // MainPage
            // 
            this.MainPage.Controls.Add(this.LoadButton);
            this.MainPage.Controls.Add(this.ProfileList);
            this.MainPage.Controls.Add(this.SaveButton);
            resources.ApplyResources(this.MainPage, "MainPage");
            this.MainPage.Name = "MainPage";
            this.MainPage.UseVisualStyleBackColor = true;
            // 
            // SettingsPage
            // 
            this.SettingsPage.Controls.Add(this.Notification1);
            resources.ApplyResources(this.SettingsPage, "SettingsPage");
            this.SettingsPage.Name = "SettingsPage";
            this.SettingsPage.UseVisualStyleBackColor = true;
            // 
            // TabSelector
            // 
            this.TabSelector.BaseTabControl = this.TabControl;
            this.TabSelector.Depth = 0;
            resources.ApplyResources(this.TabSelector, "TabSelector");
            this.TabSelector.MouseState = MaterialSkin.MouseState.HOVER;
            this.TabSelector.Name = "TabSelector";
            this.TabSelector.Click += new System.EventHandler(this.TabSelector_Click);
            // 
            // Notification1
            // 
            resources.ApplyResources(this.Notification1, "Notification1");
            this.Notification1.Depth = 0;
            this.Notification1.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(222)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.Notification1.MouseState = MaterialSkin.MouseState.HOVER;
            this.Notification1.Name = "Notification1";
            // 
            // Switcher
            // 
            resources.ApplyResources(this, "$this");
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.SystemColors.ControlDarkDark;
            this.Controls.Add(this.TabSelector);
            this.Controls.Add(this.TabControl);
            this.Cursor = System.Windows.Forms.Cursors.Default;
            this.ForeColor = System.Drawing.SystemColors.ControlText;
            this.Name = "Switcher";
            this.Sizable = false;
            this.Load += new System.EventHandler(this.Switcher_Load);
            this.TabControl.ResumeLayout(false);
            this.MainPage.ResumeLayout(false);
            this.MainPage.PerformLayout();
            this.SettingsPage.ResumeLayout(false);
            this.SettingsPage.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.ListView ProfileList;
        private MaterialSkin.Controls.MaterialFlatButton SaveButton;
        private MaterialSkin.Controls.MaterialFlatButton LoadButton;
        private MaterialSkin.Controls.MaterialTabControl TabControl;
        private System.Windows.Forms.TabPage MainPage;
        private System.Windows.Forms.TabPage SettingsPage;
        private MaterialSkin.Controls.MaterialTabSelector TabSelector;
        private MaterialSkin.Controls.MaterialLabel Notification1;
    }
}

