//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfileSwitcher.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProfileSwitcher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Are you have logged-in to an account beforehand?.
        /// </summary>
        internal static string AccountLoginError {
            get {
                return ResourceManager.GetString("AccountLoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account not found.
        /// </summary>
        internal static string AccountNotFound {
            get {
                return ResourceManager.GetString("AccountNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BinaryData is Null.
        /// </summary>
        internal static string BinaryDataNull {
            get {
                return ResourceManager.GetString("BinaryDataNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete [{0}].
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Are you sure the game is installed?.
        /// </summary>
        internal static string GameInstallationError {
            get {
                return ResourceManager.GetString("GameInstallationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close the game before switching accounts.
        /// </summary>
        internal static string GameOpenError {
            get {
                return ResourceManager.GetString("GameOpenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close the game before Deleting accounts.
        /// </summary>
        internal static string GameOpenError2 {
            get {
                return ResourceManager.GetString("GameOpenError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Height.
        /// </summary>
        internal static string InvalidHeight {
            get {
                return ResourceManager.GetString("InvalidHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Text.
        /// </summary>
        internal static string InvalidText {
            get {
                return ResourceManager.GetString("InvalidText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Width.
        /// </summary>
        internal static string InvalidWidth {
            get {
                return ResourceManager.GetString("InvalidWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name the Profile.
        /// </summary>
        internal static string NameTheProfile {
            get {
                return ResourceManager.GetString("NameTheProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Accounts Loaded.
        /// </summary>
        internal static string NoAccountsLoaded {
            get {
                return ResourceManager.GetString("NoAccountsLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Profile/s Loaded..
        /// </summary>
        internal static string ProfilesLoaded {
            get {
                return ResourceManager.GetString("ProfilesLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genshin Impact registry key not found..
        /// </summary>
        internal static string RegistryKeyNotFound {
            get {
                return ResourceManager.GetString("RegistryKeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename the Profile.
        /// </summary>
        internal static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select account.
        /// </summary>
        internal static string SelectAccount {
            get {
                return ResourceManager.GetString("SelectAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch success!.
        /// </summary>
        internal static string SwitchSuccess {
            get {
                return ResourceManager.GetString("SwitchSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to [{0}].
        /// </summary>
        internal static string SwitchTo {
            get {
                return ResourceManager.GetString("SwitchTo", resourceCulture);
            }
        }
    }
}
